cache: apt
sudo: true
language: python
python:
  - 2.7
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; # grab miniconda
  - bash miniconda.sh -b -p $HOME/miniconda # install miniconda
  - export PATH="$HOME/miniconda/bin:$PATH" # add it to the path
  - conda config --set always_yes yes --set changeps1 no # we want it to always do yes, and start a new console
  - conda update -q conda # update this quietly
  - conda install pyyaml
  - conda info -a # and print the info

env:
  - TEST_ENV_NAME=test_dependencies
install: True

script:
  - conda env create --file ${TEST_ENV_NAME}.yml;
  - source activate ptychotools
  - conda install pytest # additional dependencies for the tests
  - pip install pytest-cov
  - pip install coveralls
  - echo $PYTHONPATH
  - conda list
  - python setup.py build # test that the package buikds
  - py.test build/lib/test -v -m "not ptypy" --cov test --cov-report term-missing # now run the tests

after_script:
  - coveralls


